#!/usr/bin/env bash

# Show that `dicegen` displays the word list when requested.

set -euo pipefail
shopt -s extglob

source ./tests/lib/init.bash

for wordlist_file in ./share/wordlists/roll+([0-9]); do
    length=${wordlist_file##*/roll}
    for opt in -l --list; do
        if ! cmp -s -- "$wordlist_file" <(dicegen -"$length" "$opt"); then
            printf "output for %s did not match wordlist: %q\n" "$opt" "$wordlist_file"
            exit 1
        fi
    done
done
