#!/usr/bin/env bash

# Show that `dicegen` displays help when requested.

set -euo pipefail

source ./tests/lib/init.bash

pattern=".*Usage:.*"

for opt in -h --help; do
    assert_success assert_stdout_match "$pattern" dicegen "$opt"
done
