#!/usr/bin/env bash

# Show that `dicegen` uses the long word list by default.

set -euo pipefail

source ./tests/lib/init.bash

read -r roll expected_word < <(tail -n1 ./share/wordlists/roll5)

word=$(dicegen <<<"$roll")

assert_equal "$word" "$expected_word"
