#!/usr/bin/env bash

# Show that `dicegen` displays help when requested.

set -euo pipefail

source "$TESTS_LIB_DIR"/init.bash

pattern=".*Usage:.*"

for opt in -h --help; do
    assert_success assert_stdout_match "$pattern" dicegen "$opt"
done
