#!/usr/bin/env bash

# Show that `dicegen` displays the word list when requested.

set -euo pipefail
shopt -s extglob

source "$TESTS_LIB_DIR"/init.bash

for data_file in "$DICEWARE_DATA_DIR"/wordlists/roll+([0-9]); do
    length=${data_file##*/roll}
    for opt in -l --list; do
        if ! diff -u -- "$data_file" <(dicegen -"$length" "$opt"); then
            printf "output for %s did not match data file: %q\n" "$opt" "$data_file"
        fi
    done
done
