#!/usr/bin/env bash

# Show that `dicegen` will not accept invalid digits.

set -euo pipefail

source ./tests/lib/init.bash

count=$((RANDOM % 15 + 5))
diceroll -- "$count" >"$TEMP_DIR"/input

line=$((RANDOM % count + 1))
column=$((RANDOM % 5 + 1))

# Replace a random digit with an invalid one.
sed -i "${line}s/./9/${column}" -- "$TEMP_DIR"/input

printf -v stderr \
    "dicegen: line $line must only contain digits between 1 and 6\n"

assert_failure assert_stderr "$stderr" \
    dicegen "$TEMP_DIR"/input
