#!/usr/bin/env bash

# Show that `dicegen` can accept input as a file argument.

set -euo pipefail
shopt -s extglob

source ./tests/lib/init.bash

wordlist_file=./share/wordlists/roll5

diceroll -- $((RANDOM % 15 + 5)) >"$TEMP_DIR"/input
dicegen "$TEMP_DIR"/input | tr ' ' '\n' >"$TEMP_DIR"/output

while read -r roll word; do
    if ! expected_word=$(grep -m1 "^$roll\b" "$wordlist_file" | cut -d$'\t' -f2); then
        printf "cound not find roll %q in wordlist: %q\n" "$roll" "$wordlist_file"
        exit 1
    fi
    assert_equal "$word" "$expected_word"
done < <(paste -- "$TEMP_DIR"/{input,output})
