#!/usr/bin/env bash

# Show that `dicegen` will not accept lines that are too long.

set -euo pipefail

source ./tests/lib/init.bash

count=$((RANDOM % 15 + 5))
diceroll -- "$count" >"$TEMP_DIR"/input

line=$((RANDOM % count + 1))

# Make a random line one character too long.
sed -i "${line}s/$/1/" -- "$TEMP_DIR"/input

printf -v stderr \
    "dicegen: line $line must be exactly 5 digits\n"

assert_failure assert_stderr "$stderr" \
    dicegen "$TEMP_DIR"/input
