#!/usr/bin/env bash

# Show that `dicegen` can accept input as a file argument.

set -euo pipefail
shopt -s extglob

source ./tests/lib/init.bash

for wordlist_file in ./share/wordlists/roll+([0-9]); do
    length=${wordlist_file##*/roll}
    count=$((RANDOM % 15 + 5))

    diceroll -"$length" -- "$count" >"$TEMP_DIR"/input

    dicegen -"$length" "$TEMP_DIR"/input | tr ' ' '\n' >"$TEMP_DIR"/output

    while read -r roll word; do
        if ! expected_word=$(grep -m1 "^$roll\b" "$wordlist_file" | cut -d$'\t' -f2); then
            printf "cound not find roll %q in wordlist: %q\n" "$roll" "$wordlist_file"
            exit 1
        fi
        assert_equal "$word" "$expected_word"
    done < <(paste -- "$TEMP_DIR"/{input,output})
done
