#!/usr/bin/env bash

# Show that `dicegen` outputs the expected words.

set -euo pipefail
shopt -s extglob

source ./tests/lib/init.bash

for wordlist_file in ./share/wordlists/roll+([0-9]); do
    length=${wordlist_file##*/roll}
    count=$((RANDOM % 15 + 5))

    readarray -t rolls < <(diceroll -"$length" -- "$count")

    read -ra words < <(printf "%s\n" "${rolls[@]}" | dicegen -"$length")

    for ((i = 0; i < ${#rolls[@]}; i++)); do
        if ! expected_word=$(grep -m1 "^${rolls[i]}\b" "$wordlist_file" | cut -d$'\t' -f2); then
            printf "cound not find roll %q in wordlist: %q\n" "${rolls[i]}" "$wordlist_file"
            exit 1
        fi
        assert_equal "${words[i]}" "$expected_word"
    done
done
