#!/usr/bin/env bash

# Show that `diceroll` displays the version when requested.

set -euo pipefail

source "$TESTS_LIB_DIR"/init.bash

version=$(<"$LIB_DIR"/version)$'\n'

for opt in -v --version; do
    assert_success assert_stdout "$version" diceroll "$opt"
done
