#!/usr/bin/env bash

# Show that `diceroll` displays the version when requested.

set -euo pipefail

source ./tests/lib/init.bash

version=$(<./lib/version)$'\n'

for opt in -v --version; do
    assert_success assert_stdout "$version" diceroll "$opt"
done
