#!/usr/bin/env bash

set -euo pipefail

self_name=${0##*/}

roll_count=${1:?missing roll count}
wordlist_file=${2:?missing wordlist file}

num_lines=$(wc -l <"$wordlist_file")
expected_num_lines=$((6 ** roll_count))

if ((num_lines != expected_num_lines)); then
    printf "%s: expected file to have %d lines, but it had %d: %q\n" \
        "$self_name" "$expected_num_lines" "$num_lines" "$wordlist_file" >&2
fi

line=1
declare -A seen_rolls=() seen_words=()

while read -r roll word; do
    if [[ -z $roll ]]; then
        printf "%s: roll on line %d is missing\n" "$self_name" "$line" >&2
        exit 1
    fi
    if ((${#roll} != roll_count)); then
        printf "%s: roll on line %d length is incorrect: %d != %d\n" "$self_name" "$line" "${#roll}" "$roll_count" >&2
        exit 1
    fi
    if [[ ! $roll =~ ^[1-6]+$ ]]; then
        printf "%s: roll on line %d contains invalid digit (must be 1-6): %s\n" "$self_name" "$line" "$roll" >&2
        exit 1
    fi
    if [[ -v seen_rolls[$roll] ]]; then
        printf "roll %q is on multiple lines: %q (lines %d and %d)\n" "$roll" "$wordlist_file" "$line" "${seen_rolls[$roll]}" >&2
        exit 1
    fi
    seen_rolls[$roll]=$line

    if [[ -z $word ]]; then
        printf "%s: word on line %d is missing\n" "$self_name" "$line" >&2
        exit 1
    fi
    if [[ ! $word =~ ^[a-z-]+$ ]]; then
        printf "%s: word on line %d is not lowercase alphabetic: %s\n" "$self_name" "$line" "$word" >&2
        exit 1
    fi
    if [[ -v seen_words[$word] ]]; then
        printf "word %q is on multiple lines: %q (lines %d and %d)\n" "$word" "$wordlist_file" "$line" "${seen_words[$word]}" >&2
        exit 1
    fi
    seen_words[$word]=$line

    line=$((line + 1))

done <"$wordlist_file"
