#!/usr/bin/env bash

set -euo pipefail

bin_dir=$HOME/.local/bin

mkdir -p "$bin_dir"
ln -vsfnr -t "$bin_dir" ./bin/*

data_dir=$HOME/.local/share/diceware

mkdir -p "$data_dir"
ln -vsfnr -t "$data_dir" ./data/*
