#!/usr/bin/env bash

set -euo pipefail

PREFIX=${PREFIX:-/usr/local}

sed -i \
    -e "1s:#\!.*/env \(.*\)$:#\!/usr/bin/\1:" \
    ./bin/*

sed -i \
    -e "s:\./bin\b:$PREFIX/bin:g" \
    -e "s:\./lib\b:$PREFIX/lib/diceware:g" \
    ./bin/* ./lib/* ./man/*
