#!/usr/bin/env bash

set -euo pipefail

PREFIX=${PREFIX:-/usr/local}

if [[ $PREFIX == /usr ]]; then
    etc_dir=/etc
else
    etc_dir=$PREFIX/etc
fi

sed -i "1s:#\!.*/env \(.*\)$:#\!/usr/bin/\1:" ./bin/*
sed -i -e "s:/usr/local/etc:$etc_dir:g" -e "s:/usr/local:$PREFIX:g" ./bin/* ./lib/* ./man/*
