#!/usr/bin/env bash

set -euo pipefail

PREFIX=${PREFIX:-/usr/local}

sed -i "1s:#\!.*/env \(.*\)$:#\!/usr/bin/\1:" ./bin/*

sed -i \
    -e "s:\./bin:$PREFIX/bin:g" \
    -e "s:\./lib:$PREFIX/lib/diceware:g" \
    ./bin/* ./lib/* ./man/*
