#!/usr/bin/env bash

set -euo pipefail

export PATH=$PWD/bin:$PWD/tests/bin:$PATH

self_name=${0##*/}

test_file=${1:?missing test file}

TEMP_DIR=$(mktemp -td -- "$self_name.$$".XXXXXXXXXX)
trap 'rm -rf -- "$TEMP_DIR"' EXIT

export TEMP_DIR

if ! "$test_file"; then
    printf "test failed: %q\n" "$test_file" >&2
    exit 1
fi
