#!/usr/bin/env bash

set -euo pipefail
shopt -s extglob

self_name=${0##*/}

export PATH=$PWD/bin:$PATH
export DICEGEN_DATA_DIR=$PWD/data

for data_file in "$DICEGEN_DATA_DIR"/words/roll+([0-9]); do
    printf "Testing data file: %q\n" "$data_file"

    length=${data_file##*/roll}

    num_lines=$(wc -l <"$data_file")
    expected_num_lines=$((6 ** length))
    if ((num_lines != expected_num_lines)); then
        printf "%s: expected file to have %d lines, but it only had %d\n" "$self_name" "$expected_num_lines" "$num_lines" >&2
        exit 1
    fi

    line=0
    declare -A seen_rolls=() seen_words=() word_for_roll=()

    while read -r roll word; do
        line=$((line + 1))

        if [[ -z $roll ]]; then
            printf "%s: roll on line %d is missing\n" "$self_name" "$line" >&2
            exit 1
        fi
        if ((${#roll} != length)); then
            printf "%s: roll on line %d length is incorrect: %d != %d\n" "$self_name" "$line" "${#roll}" "$length" >&2
            exit 1
        fi
        if [[ ! $roll =~ ^[1-6]+$ ]]; then
            printf "%s: roll on line %d contains invalid digit (must be 1-6): %s\n" "$self_name" "$line" "$roll" >&2
            exit 1
        fi
        if [[ -v seen_rolls[$roll] ]]; then
            printf "%s: roll on line %d was also seen on line %d: %s\n" "$self_name" "$line" "${seen_rolls[$roll]}" "$roll" >&2
            exit 1
        fi
        seen_rolls[$roll]=$line

        if [[ -z $word ]]; then
            printf "%s: word on line %d is missing\n" "$self_name" "$line" >&2
            exit 1
        fi
        if [[ ! $word =~ ^[a-z-]+$ ]]; then
            printf "%s: word on line %d is not lowercase alphabetic: %s\n" "$self_name" "$line" "$word" >&2
            exit 1
        fi
        if [[ -v seen_words[$word] ]]; then
            printf "%s: word on line %d was also seen on line %d: %s\n" "$self_name" "$line" "${seen_words[$word]}" "$word" >&2
            exit 1
        fi
        seen_words[$word]=$line

        word_for_roll[$roll]=$word

    done <"$data_file"

    count=$((RANDOM % 15 + 5))

    readarray -t rolls < <(diceroll "$length" "$count")

    if ((${#rolls[@]} != count)); then
        printf "%s: diceroll count is incorrect: %d != %d\n" "$self_name" "${#rolls[@]}" "$count" >&2
        exit 1
    fi

    for ((i = 0; i < ${#rolls[@]}; i++)); do
        if ((${#rolls[i]} != length)); then
            printf "%s: diceroll line %d length is incorrect: %d != %d\n" "$self_name" $((i + 1)) "${#rolls[i]}" "$length" >&2
            exit 1
        fi
    done

    read -ra words < <(printf "%s\n" "${rolls[@]}" | dicegen "$length")

    for ((i = 0; i < ${#rolls[@]}; i++)); do
        if [[ -z ${rolls[i]} ]]; then
            printf "%s: dicegen word %d was empty\n" "$self_name" $((i + 1)) >&2
            exit 1
        fi
        expected_word=${word_for_roll[${rolls[i]}]}
        if [[ -z $expected_word ]]; then
            printf "%s: dicegen word %d (%q) not found in file\n" "$self_name" $((i + 1)) "${words[i]}" >&2
            exit 1
        fi
        if [[ ${words[i]} != "$expected_word" ]]; then
            printf "%s: dicegen word %d did not match expected: %q != %q\n" "$self_name" $((i + 1)) "${words[i]}" "$expected_word" >&2
            exit 1
        fi
    done
done
