#!/usr/bin/env bash

set -euo pipefail

self_name=${0##*/}

usage="Run tests.

Usage:
    $self_name [OPTIONS] [PATTERN...]

Options:
    -h    show this help message and exit

    -v    print every test that's run, regardless of failures
    -i    ignore case when matching PATTERN

Arguments:
    PATTERN    only test files matching PATTERN
"

unset verbose
find_opt="path"

while getopts "vih" opt; do
    case $opt in
        v) verbose=1 ;;
        i) find_opt="ipath" ;;
        h)
            printf "%s\n" "$usage"
            exit
            ;;
        *) exit 64 ;;
    esac
done
shift $((OPTIND - 1))

find_opts=()

if (($# > 0)); then
    pat_opts=()
    for pattern in "$@"; do
        pat_opts+=(-o -"$find_opt" "*$pattern*")
    done
    find_opts+=('(' "${pat_opts[@]:1}" ')')
fi

readarray -t -d '' test_files < <(
    find ./tests/suites -type f -executable "${find_opts[@]}" -print0
)

export TIMEFORMAT="Ran ${#test_files[@]} tests in %3Rs"

time printf "%s\0" "${test_files[@]}" | parallel -r0 -j0 ${verbose:+-v} --shuf ./scripts/test1
