#!/usr/bin/env bash

set -euo pipefail

for url_file in ./config/wordlists/*; do
    url=$(<"$url_file")
    data_file=./data/${url_file#*/config/}
    mkdir -p "$(dirname "$data_file")"
    printf "downloading: %s => %s\n" "$url" "$data_file"
    curl -o "$data_file" -z "$data_file" "$url"
done
