#!/usr/bin/env bash

set -euo pipefail

for config_file in ./config/wordlists/*; do
    url=$(<"$config_file")
    wordlist_file=./share/${config_file#*/config/}

    printf "Downloading: %s => %s\n" "$url" "$wordlist_file"

    mkdir -p "$(dirname "$wordlist_file")"
    curl -o "$wordlist_file" -z "$wordlist_file" "$url"
done
