#!/usr/bin/env bash

set -euo pipefail

self_name=${0##*/}

usage="Print or increment the project version.

Usage:
    $self_name [OPTIONS]

Options:
    -h    show this help message and exit

    -M    increment the major version
    -m    increment the minor version
    -p    increment the patch version

All increment options are mutually exclusive and the last specified wins.
If no increment option is given, the current version will be printed to stdout.
"

unset bump

while getopts "Mmph" opt; do
    case $opt in
        M) bump=0 ;;
        m) bump=1 ;;
        p) bump=2 ;;
        h)
            printf "%s\n" "$usage"
            exit
            ;;
        *) exit 64 ;;
    esac
done
shift $((OPTIND - 1))

labels=(major minor patch)

version_file=./lib/version

if [[ -f $version_file ]]; then
    IFS=. read -ra parts <"$version_file"
else
    parts=(0 0 0)
fi

if [[ -v bump ]]; then
    parts[bump]=$((parts[bump] + 1))
    for ((i = bump + 1; i < ${#parts[@]}; i++)); do
        parts[i]=0
    done
fi

IFS=. version=${parts[*]}

printf "%s\n" "$version"

if [[ ! -v bump ]]; then
    exit
fi

printf "%s\n" "$version" >"$version_file"

git add "$version_file"

git commit -e \
    -m "build(release): bump version to $version" \
    -m "This is a ${labels[$bump]} version change."

git tag -a -m "Release version $version" v"$version"
